# Generated by Django 2.2.5 on 2019-10-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0003_session_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='position',
            new_name='content_id',
        ),
    ]
