# Generated by Django 2.2.5 on 2019-10-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0004_auto_20191026_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, db_column='image', upload_to='statistics_app/pictures'),
        ),
    ]
