# Generated by Django 2.2.5 on 2019-10-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0005_session_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='image',
        ),
        migrations.AddField(
            model_name='session',
            name='image_path',
            field=models.CharField(blank=True, db_column='image_path', max_length=255),
        ),
    ]
