# Generated by Django 2.2.5 on 2019-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0007_result_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='image_path',
        ),
        migrations.AddField(
            model_name='result',
            name='image',
            field=models.ImageField(blank=True, db_column='image', upload_to='statistics_app/pictures'),
        ),
    ]
