# Generated by Django 2.2.5 on 2019-10-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0008_auto_20191026_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='image',
            field=models.ImageField(blank=True, db_column='image', upload_to='azure_app/pictures'),
        ),
    ]
