# Generated by Django 2.2.5 on 2019-10-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0009_auto_20191026_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='emotion_0',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='emotion_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='emotion_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='emotion_3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='emotion_4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='emotion_5',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='emotion_6',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='emotion_7',
            field=models.FloatField(null=True),
        ),
    ]
