# Generated by Django 2.2.5 on 2019-10-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0010_auto_20191026_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='datestring',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
