# Generated by Django 2.2.5 on 2019-10-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0011_session_datestring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='datestring',
        ),
    ]
