# Generated by Django 2.2.5 on 2019-10-26 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tale_app', '0010_auto_20191026_1837'),
        ('statistics_app', '0012_remove_session_datestring'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('session', 'content')},
        ),
    ]
