# Generated by Django 2.2.5 on 2019-10-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=128, null=True)),
            ],
            options={
                'db_table': 'Content',
            },
        ),
        migrations.CreateModel(
            name='Tale',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=128, null=True)),
                ('image', models.ImageField(blank=True, db_column='image', upload_to='tale_app/pictures')),
            ],
            options={
                'db_table': 'Tale',
            },
        ),
    ]
