# Generated by Django 2.2.5 on 2019-10-26 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tale_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='name',
        ),
        migrations.AddField(
            model_name='content',
            name='mp4',
            field=models.CharField(blank=True, db_column='mp4', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.IntegerField(db_column='order', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='taleid',
            field=models.ForeignKey(db_column='taleid', default=0, on_delete=django.db.models.deletion.CASCADE, to='tale_app.Tale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='targetemotion',
            field=models.IntegerField(db_column='targetemotion', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='taskid',
            field=models.IntegerField(blank=True, db_column='taskid', null=True),
        ),
        migrations.AlterField(
            model_name='tale',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=128, null=True),
        ),
    ]
