# Generated by Django 2.2.5 on 2019-10-26 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tale_app', '0002_auto_20191026_0536'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='content',
        ),
        migrations.AlterModelTable(
            name='tale',
            table='tale',
        ),
    ]
