# Generated by Django 2.2.5 on 2019-10-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tale_app', '0003_auto_20191026_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='mp4',
            field=models.FileField(db_column='mp4', null=True, upload_to='tale_app/videos'),
        ),
    ]
