# Generated by Django 2.2.5 on 2019-10-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tale_app', '0005_auto_20191026_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='taskimage',
            field=models.ImageField(blank=True, db_column='image', upload_to='tale_app/pictures'),
        ),
        migrations.AddField(
            model_name='content',
            name='tasktext',
            field=models.CharField(blank=True, db_column='name', max_length=128, null=True),
        ),
    ]
