# Generated by Django 2.2.5 on 2019-10-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tale_app', '0006_auto_20191026_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.IntegerField(db_column='type', default=0),
            preserve_default=False,
        ),
    ]
