# Generated by Django 2.2.5 on 2019-10-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tale_app', '0007_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='taskimage',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='tale_app/pictures'),
        ),
    ]
