# Generated by Django 2.2.5 on 2019-10-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tale_app', '0008_auto_20191026_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='mp4',
            field=models.FileField(blank=True, db_column='mp4', null=True, upload_to='tale_app/videos'),
        ),
    ]
