# Generated by Django 2.2.5 on 2019-10-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tale_app', '0009_auto_20191026_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='targetemotion',
            field=models.IntegerField(blank=True, db_column='targetemotion'),
        ),
    ]
